Document: pynacl
Title: Debian pynacl Manual
Author: <insert document author here>
Abstract: This manual describes what pynacl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pynacl/pynacl.sgml.gz

Format: postscript
Files: /usr/share/doc/pynacl/pynacl.ps.gz

Format: text
Files: /usr/share/doc/pynacl/pynacl.text.gz

Format: HTML
Index: /usr/share/doc/pynacl/html/index.html
Files: /usr/share/doc/pynacl/html/*.html
